package com.example.account.receivable.Common.Premission;

public enum Permission {

    // DASHBOARD
    VIEW_DASHBOARD,


    // CUSTOMERS
    VIEW_CUSTOMERS,
    CREATE_CUSTOMER,
    EDIT_CUSTOMER,
    DELETE_CUSTOMER,


    // INVOICES
    VIEW_INVOICES,
    CREATE_INVOICE,
    EDIT_INVOICE,
    DELETE_INVOICE,
    APPROVE_INVOICE,


    // PAYMENTS
    VIEW_PAYMENTS,
    APPLY_PAYMENT,
    APPROVE_PAYMENT,

    //EOB INTEGRATION
    VIEW_INTEGRATION,


    // AGING & REPORTS
    VIEW_AGING_REPORTS,
    VIEW_PAYMENT_REPORTS,
    VIEW_INVOICE_REPORTS,


    // COLLECTIONS
    VIEW_COLLECTIONS,

    // REMINDER
    VIEW_REMINDER,
    SEND_REMINDER,

    // PROMISE TO PAY
    VIEW_PROMISE_TO_PAY,
    CREATE_PROMISE_TO_PAY,

    // DISPUTE
    VIEW_DISPUTE,
    CREATE_DISPUTE,



    // CREDIT MEMOS
    VIEW_MEMOS,
    CREATE_MEMOS,
    APPROVE_MEMOS,


    // WRITE OFF
    VIEW_WRITE_OFF,
    CREATE_WRITE_OFF,
    APPROVE_WRITE_OFF,


    // SECURITY_REPORT , USERS , ROLES , MFA
    VIEW_SECURITY_REPORT,
    VIEW_USER,
    INVITE_USER,
    VIEW_MFA,
    VIEW_ROLES,
    CREATE_ROLES,
    UPDATE_ROLE,


    //SETUP AND ADMIN
    // COMPANY
    VIEW_COMPANY,
    CREATE_COMPANY,
    DELETE_COMPANY,
    UPDATE_COMPANY,

    // Bank 
    VIEW_BANK_ACCOUNT,
    CREATE_BANK_ACCOUNT,
    UPDATE_BANK_ACCOUNT,

    // AR Code
    VIEW_AR_CODE,
    CREATE_AR_CODE,
    UPDATE_AR_CODE,
    DELETE_AR_CODE,

    //GL Codes
    VIEW_GL_CODE,
    CREATE_GL_CODE,
    UPDATE_GL_CODE,

    //PAYMENT TERMS
    VIEW_PAYMENT_TERMS,
    CREATE_PAYMENT_TERMS,
    UPDATE_PAYMENT_TERMS,
    DELETE_PAYMENT_TERMS,

    //LATE FEE
    VIEW_LATE_FEE,
    UPDATE_LATE_FEE,
    CREATE_LATE_FEE,
    DELETE_LATE_FEE,

    //AGING CODE
    VIEW_AGING_CODE,
    UPDATE_AGING_CODE,
    CREATE_AGING_CODE,
    DELETE_AGING_CODE,

    // GL Transactions
    VIEW_GL_TRANSACTION,
    CREATE_GL_TRANSACTION
}

