services:
  account-receivable-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: account-receivable
    container_name: account-receivable

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: sql

    ports:
      - "8080:8080"

    volumes:
      - ./logs:/app/logs
